### PR TITLE
Fix npm audit warnings

### PR DESCRIPTION
**Pull request by nemzes**
Adding Sentencer as a dependency currently results in an `npm audit` warning:
```➤ npm audit

                       === npm audit security report ===

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ lodash                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.17.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ sentencer                                                    │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ sentencer > lodash                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/577                       │
└───────────────┴──────────────────────────────────────────────────────────────┘```

This PR upgrades dependencies.

### CODE REVIEW

**Comment by mikemimik** [comment]
@kylestetz is it possible for you to merge this PR and publish version `0.2.0` of this package. It would be great to remove the audit issue.

If this PR isn't acceptable, could you provide feedback so that it can be approved and merged. Thanks :)

**Comment by nemzes** [comment]
@mikemimik I've given up and made a fork: https://github.com/nemzes/phraseit

**Comment by mikemimik** [comment]
Thanks @nemzes I'll leverage your plugin instead. Cheers!

**Comment by kylestetz** [comment]
Ah so sorry folks, I totally dropped the ball on this. Thanks for your PR and sorry you had to make that fork!

**Comment by kylestetz** [comment]
Just merged this and published `0.2.0`. :v:

**Pull request merged**
